In [25]:
import json
import pandas as pd
import numpy as np

with open('planes_data.json','r') as read_file:
    planes = json.load(read_file)
    read_file.close()

pd.read_json('planes_data.json')

       Airbus A220-100  Airbus A220-300  ...  Як-42  Як-242 (МС-21)
km                4000             4000  ...   1700            5000
seats              117              140  ...    120             157

[2 rows x 134 columns]

In [2]:
import matplotlib.pyplot as plt
plt.scatter([planes[i]['km'] for i in planes.keys()],[planes[i]['seats'] for i in planes.keys()])
plt.show()

ModuleNotFoundError: No module named 'matplotlib'